### ISSUE TITLE
Status is stuck on "Loading"

### ISSUE THREAD

**Issue by BevanG** [mwiedemeyer/VSCodeDevOpsBuildStatus#1]
Installed the extension and the Status is stuck on "Loading". Have tried several Repos and Projects and it's the same.

Am I missing a configuration somewhere or should the extension automatically find what it needs to?

**Comment by mwiedemeyer** [comment]
Have you configured the correct values for your org and access token?
You can first try to reset the values by open the command palette (CTRL+SHIFT+P) and search for "DevOpsBuildStatus: Reset configuration"

If this does not help, can you please try to login with a browser to your DevOps org and then open this link:
`https://dev.azure.com/YOUR_ORG/_apis/distributedtask/resourceusage?parallelismTag=Private&poolIsHosted=true&includeRunningRequests=true`
You should get a json text response.

**Comment by codexponent** [comment]
Hi, @mwiedemeyer . I am also facing the same problem as @BevanG. Reset doesn't do much.
You have pasted a link above. What should we look into the JSON text response for the solution?

**Comment by mwiedemeyer** [comment]
You should see something like this:
```json
{"resourceLimit":{"resourceLimitsData":{"FreeCount":"0","PurchasedCount":"3"},"hostId":"6fb14e79-xxxx-xxxx-xxxx-xxxxxxxxxxxx","parallelismTag":"Private","isHosted":true,"totalCount":3,"totalMinutes":1800,"isPremium":true},"usedCount":0,"usedMinutes":0}
```

Have you filled in the correct values for ORG and access token?
In the first prompt enter just the ORG part of the url: https://dev.azure.com/ORG so only enter `ORG`
Then you need a personal access token. It must be a "full access" token.
![image](https://user-images.githubusercontent.com/4295189/119608308-09dcc580-bdf6-11eb-90b2-a6aaba849be0.png)

**Comment by codexponent** [comment]
I got this json. I can see that my premium is false.
{"resourceLimit":{"resourceLimitsData":{"FreeCount":"0","PurchasedCount":"0"},"hostId":"xxxx-xxxx-xxxx-xxxx-xxxx","parallelismTag":"Private","isHosted":true,"totalCount":0,"totalMinutes":1800,"isPremium":false},"usedCount":0,"usedMinutes":0}

Update: I Disable and Enabled the extension again with the same 'ORG' and 'PAT" and it worked now. Thank you for your response. I will let you know if any problem arises again.
![image](https://user-images.githubusercontent.com/13358738/119611125-fb080a00-be19-11eb-8e59-1e313273d9ac.png)
